import { useState } from "react";
import {
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Terminal,
  Copy,
  Check,
  Cpu,
  FolderCheck,
  CheckSquare,
  Square,
  Sparkles,
} from "lucide-react";
import { EngineInfo } from "../../types";
import { LoomLogo } from "../LoomLogo";

interface OnboardingWizardProps {
  engines: EngineInfo[];
  onComplete: () => void;
}

export const OnboardingWizard = ({ engines, onComplete }: OnboardingWizardProps) => {
  const [currentStep, setCurrentStep] = useState<number>(1);
  const [termsAccepted, setTermsAccepted] = useState<boolean>(false);
  const [copiedCmd, setCopiedCmd] = useState<string | null>(null);

  const copyCommand = (id: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCmd(id);
    setTimeout(() => setCopiedCmd(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-[#0A0A0B]/85 backdrop-blur-md flex items-center justify-center p-4 select-none">
      <div className="w-[760px] max-w-[95vw] bg-[#141518] border border-[#26282D] rounded-[10px] shadow-2xl flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="p-6 border-b border-[#26282D] bg-[#141518] flex items-center justify-between">
          <div className="flex items-center gap-3.5">
            <LoomLogo size={36} />
            <div>
              <div className="text-base font-bold text-[#E8E9EB] flex items-center gap-2.5">
                <span>Welcome to Loom</span>
                <span className="text-[11px] px-2 py-0.5 rounded bg-[#A3E635]/15 text-[#A3E635] border border-[#A3E635]/30 font-mono font-semibold">
                  Setup & Doctor
                </span>
              </div>
              <div className="text-[12px] text-[#9CA0A8] mt-0.5">
                Multi-engine load testing workstation configuration & compliance
              </div>
            </div>
          </div>

          {/* Stepper Dots */}
          <div className="flex items-center gap-2 font-mono text-[12px]">
            {[1, 2, 3, 4].map((step) => (
              <div
                key={step}
                className={`w-7 h-7 rounded-full flex items-center justify-center text-[11px] font-bold border transition-colors ${
                  currentStep === step
                    ? "bg-[#A3E635] text-[#0A0A0B] border-[#A3E635] shadow-[0_0_10px_rgba(163,230,53,0.4)]"
                    : currentStep > step
                    ? "bg-[#4ADE80]/20 text-[#4ADE80] border-[#4ADE80]/40"
                    : "bg-[#1C1E22] text-[#5C6068] border-[#26282D]"
                }`}
              >
                {currentStep > step ? "✓" : step}
              </div>
            ))}
          </div>
        </div>

        {/* Body Content */}
        <div className="p-6 max-h-[500px] overflow-y-auto">
          {/* Step 1: Terms & Conditions */}
          {currentStep === 1 && (
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2 text-[#A3E635] text-[14px] font-semibold">
                <ShieldCheck className="w-5 h-5" />
                <span>Terms of Service & EULA Agreement</span>
              </div>
              <p className="text-[13px] text-[#9CA0A8] leading-relaxed">
                Please review the terms and responsible testing policies before using Loom on your local machine.
              </p>

              <div className="bg-[#0A0A0B] p-4 rounded-[6px] border border-[#26282D] font-mono text-[12px] text-[#E8E9EB] leading-relaxed h-[230px] overflow-y-auto select-text shadow-inner">
                <div className="font-bold text-[#A3E635] mb-2.5 text-[13px]">LOOM END USER LICENSE AGREEMENT (EULA)</div>
                <p className="mb-2.5">
                  1. <b className="text-white">Permitted Use & Authorization:</b> Loom is designed strictly for testing systems you own, manage, or have explicit written authorization to test. Performing unauthorized stress tests against third-party servers is strictly prohibited.
                </p>
                <p className="mb-2.5">
                  2. <b className="text-white">Subprocess & License Isolation:</b> Core engines (Locust, Goose) operate under permissive licenses (MIT/Apache). Plugin engines (k6) are licensed under AGPL-3.0. Loom does not bundle or link copyleft binaries; all execution happens via operating system process boundaries.
                </p>
                <p className="mb-2.5">
                  3. <b className="text-white">Local-First Privacy:</b> Loom stores all test scripts, configurations, and performance metrics locally in SQLite. No telemetry is collected or sent to external servers.
                </p>
                <p>
                  4. <b className="text-white">Disclaimer:</b> The software is provided "as is" without warranty. Users bear full responsibility for simulated loads generated by this tool.
                </p>
              </div>

              {/* Agreement Checkbox */}
              <div
                onClick={() => setTermsAccepted(!termsAccepted)}
                className={`flex items-center gap-3 p-3.5 rounded-[6px] border cursor-pointer transition-all ${
                  termsAccepted
                    ? "bg-[#1C1E22] border-[#A3E635]/60 ring-1 ring-[#A3E635]/30"
                    : "bg-[#1C1E22] border-[#26282D] hover:border-[#3A3D44]"
                }`}
              >
                {termsAccepted ? (
                  <CheckSquare className="w-5 h-5 text-[#A3E635]" />
                ) : (
                  <Square className="w-5 h-5 text-[#5C6068]" />
                )}
                <span className="text-[13px] text-[#E8E9EB] select-none font-medium">
                  I have read, understood, and accept the Loom End User License Agreement and Terms of Service.
                </span>
              </div>
            </div>
          )}

          {/* Step 2: Engine Doctor & Prerequisites */}
          {currentStep === 2 && (
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2 text-[#A3E635] text-[14px] font-semibold">
                <Cpu className="w-5 h-5" />
                <span>Engine Prerequisites & Environment Doctor</span>
              </div>
              <p className="text-[13px] text-[#9CA0A8] leading-relaxed">
                Loom checks whether load testing binaries are installed and accessible via your operating system PATH.
              </p>

              <div className="flex flex-col gap-3.5">
                {engines.map((eng) => {
                  const isReady = "Ready" in eng.availability;
                  const version = "Ready" in eng.availability ? eng.availability.Ready.version : null;
                  const installHint = "NotInstalled" in eng.availability ? eng.availability.NotInstalled.install_hint : null;

                  return (
                    <div
                      key={eng.id}
                      className="p-4 rounded-[6px] bg-[#1C1E22] border border-[#26282D] flex flex-col gap-2.5 shadow-sm"
                    >
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <span
                            className={`w-3 h-3 rounded-full ${
                              isReady ? "bg-[#4ADE80] shadow-[0_0_8px_rgba(74,222,128,0.5)]" : "bg-[#F5A623]"
                            }`}
                          />
                          <span className="font-bold text-[14px] text-[#E8E9EB]">
                            {eng.display_name}
                          </span>
                          <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-[#0A0A0B] text-[#9CA0A8] border border-[#26282D] font-semibold">
                            {eng.license_tier} Tier
                          </span>
                        </div>

                        {isReady ? (
                          <span className="text-[12px] font-mono text-[#4ADE80] flex items-center gap-1.5 font-semibold">
                            <CheckCircle2 className="w-4 h-4" />
                            <span>Installed</span>
                          </span>
                        ) : (
                          <span className="text-[12px] font-mono text-[#F5A623] flex items-center gap-1.5 font-semibold">
                            <AlertTriangle className="w-4 h-4" />
                            <span>Not Found</span>
                          </span>
                        )}
                      </div>

                      {isReady && version && (
                        <div className="text-[12px] font-mono text-[#E8E9EB] bg-[#0A0A0B] p-2.5 rounded-[4px] border border-[#26282D]">
                          {version}
                        </div>
                      )}

                      {!isReady && installHint && (
                        <div className="bg-[#141518] p-3 rounded-[6px] border border-[#F5A623]/25 flex flex-col gap-2">
                          <div className="flex items-center justify-between">
                            <span className="text-[12px] text-[#F5A623] font-medium flex items-center gap-1.5">
                              <Terminal className="w-3.5 h-3.5" />
                              <span>Install Command</span>
                            </span>
                            <button
                              onClick={() =>
                                copyCommand(
                                  eng.id,
                                  eng.id === "k6" ? "winget install k6.k6" : "cargo install goose"
                                )
                              }
                              className="btn-ghost text-[11px] gap-1 px-2 py-0.5 text-[#A3E635] hover:bg-[#A3E635]/10 font-mono font-semibold"
                            >
                              {copiedCmd === eng.id ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                              <span>{copiedCmd === eng.id ? "Copied" : "Copy command"}</span>
                            </button>
                          </div>
                          <div className="text-[11px] font-mono text-[#E8E9EB] bg-[#0A0A0B] p-2 rounded-[4px] border border-[#26282D]">
                            {eng.id === "k6"
                              ? "winget install k6.k6 (or brew install k6)"
                              : "cargo install goose (or pip install goose)"}
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Step 3: PATH & Permissions Verification */}
          {currentStep === 3 && (
            <div className="flex flex-col gap-4">
              <div className="flex items-center gap-2 text-[#A3E635] text-[14px] font-semibold">
                <FolderCheck className="w-5 h-5" />
                <span>Directories & Storage Health</span>
              </div>
              <p className="text-[13px] text-[#9CA0A8] leading-relaxed">
                Loom configures local app data paths and verified permission access for SQLite and subprocesses.
              </p>

              <div className="flex flex-col gap-3 font-mono text-[12px]">
                <div className="p-3.5 rounded-[6px] bg-[#1C1E22] border border-[#26282D] flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    <CheckCircle2 className="w-4 h-4 text-[#4ADE80]" />
                    <span className="text-[#E8E9EB]">SQLite Storage (runs + telemetry metrics)</span>
                  </div>
                  <span className="text-[#4ADE80] font-semibold">Write Permission OK</span>
                </div>

                <div className="p-3.5 rounded-[6px] bg-[#1C1E22] border border-[#26282D] flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    <CheckCircle2 className="w-4 h-4 text-[#4ADE80]" />
                    <span className="text-[#E8E9EB]">Temporary Run Workspace (~/AppData/.../runs)</span>
                  </div>
                  <span className="text-[#4ADE80] font-semibold">Initialized</span>
                </div>

                <div className="p-3.5 rounded-[6px] bg-[#1C1E22] border border-[#26282D] flex items-center justify-between">
                  <div className="flex items-center gap-2.5">
                    <CheckCircle2 className="w-4 h-4 text-[#4ADE80]" />
                    <span className="text-[#E8E9EB]">Process Boundary Subprocess Isolation</span>
                  </div>
                  <span className="text-[#4ADE80] font-semibold">Enabled</span>
                </div>
              </div>
            </div>
          )}

          {/* Step 4: Ready to Launch */}
          {currentStep === 4 && (
            <div className="flex flex-col items-center text-center gap-3.5 py-8">
              <div className="w-14 h-14 rounded-full bg-[#A3E635]/15 border border-[#A3E635]/30 flex items-center justify-center text-[#A3E635] mb-2 shadow-[0_0_20px_rgba(163,230,53,0.3)]">
                <Sparkles className="w-7 h-7" />
              </div>
              <h3 className="text-xl font-bold text-[#E8E9EB]">Setup Complete</h3>
              <p className="text-[13.5px] text-[#9CA0A8] max-w-md leading-relaxed">
                Loom is configured and ready. You will now be taken directly to the <strong className="text-[#E8E9EB]">Overview Dashboard</strong> to inspect cluster health, build visual test scenarios, and run load tests.
              </p>
            </div>
          )}
        </div>

        {/* Footer Controls */}
        <div className="p-5 border-t border-[#26282D] bg-[#141518] flex items-center justify-between">
          <div>
            {currentStep > 1 && currentStep < 4 && (
              <button
                onClick={() => setCurrentStep((prev) => prev - 1)}
                className="btn-secondary text-[13px] px-4"
              >
                Back
              </button>
            )}
          </div>

          <div className="flex items-center gap-3">
            {currentStep < 4 ? (
              <button
                onClick={() => setCurrentStep((prev) => prev + 1)}
                disabled={currentStep === 1 && !termsAccepted}
                className="btn-primary text-[13px] px-5 gap-2 font-bold tracking-wide"
              >
                <span>Continue</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            ) : (
              <button
                onClick={onComplete}
                className="btn-primary text-[13px] px-6 gap-2 font-bold tracking-wide shadow-lg shadow-[#A3E635]/25"
              >
                <span>Launch Dashboard</span>
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
