import { useState } from "react";
import {
  Check,
  CheckCircle,
  Clock,
  Copy,
  FileCode,
  Globe,
  Layers,
  Repeat,
  Send,
  Sparkles,
  Trash2,
} from "lucide-react";
import { LoomButton } from "./ui/LoomButton";

export interface FlowNode {
  id: string;
  type: "start" | "http" | "think_time" | "loop" | "assertion";
  title: string;
  method?: "GET" | "POST" | "PUT" | "DELETE";
  path?: string;
  payload?: string;
  delaySeconds?: number;
  expectedStatus?: number;
  maxLatencyMs?: number;
  iterations?: number;
  x: number;
  y: number;
}

interface FlowchartBuilderViewProps {
  onExportToRunner: (scriptContent: string, engine: string) => void;
  targetHost: string;
}

const initialNodes: FlowNode[] = [
  { id: "node-1", type: "start", title: "Test Entrypoint (Load Profile)", x: 60, y: 60 },
  { id: "node-2", type: "http", title: "Homepage Browse", method: "GET", path: "/", x: 60, y: 190 },
  { id: "node-3", type: "think_time", title: "User Reading Delay", delaySeconds: 2, x: 60, y: 320 },
  {
    id: "node-4",
    type: "http",
    title: "User Login Action",
    method: "POST",
    path: "/api/v1/auth/login",
    payload: '{"username": "test_user", "password": "secure_password"}',
    x: 60,
    y: 450,
  },
  {
    id: "node-5",
    type: "assertion",
    title: "Verify 200 OK & Latency < 400ms",
    expectedStatus: 200,
    maxLatencyMs: 400,
    x: 60,
    y: 580,
  },
];

const nodeDetails: Record<Exclude<FlowNode["type"], "start">, { label: string; detail: string; icon: typeof Globe }> = {
  http: { label: "HTTP Request", detail: "GET, POST, JSON", icon: Globe },
  think_time: { label: "Think Time", detail: "Pause between steps", icon: Clock },
  assertion: { label: "Assertion", detail: "Status & latency", icon: CheckCircle },
  loop: { label: "Loop Block", detail: "Repeat transactions", icon: Repeat },
};

export const FlowchartBuilderView = ({ onExportToRunner, targetHost }: FlowchartBuilderViewProps) => {
  const [nodes, setNodes] = useState<FlowNode[]>(initialNodes);
  const [selectedNodeId, setSelectedNodeId] = useState("node-2");
  const [previewLanguage, setPreviewLanguage] = useState<"locust" | "k6">("locust");
  const [copiedScript, setCopiedScript] = useState(false);
  const selectedNode = nodes.find((node) => node.id === selectedNodeId) ?? nodes[0];

  const addNode = (type: Exclude<FlowNode["type"], "start">) => {
    const newY = nodes.length > 0 ? nodes[nodes.length - 1].y + 130 : 60;
    const id = `node-${Date.now()}`;
    const defaults: Record<Exclude<FlowNode["type"], "start">, Omit<FlowNode, "id" | "x" | "y">> = {
      http: { type: "http", title: "API Request", method: "GET", path: "/api/endpoint" },
      think_time: { type: "think_time", title: "Simulated Delay", delaySeconds: 1 },
      assertion: { type: "assertion", title: "Assert Status OK", expectedStatus: 200, maxLatencyMs: 500 },
      loop: { type: "loop", title: "Repeat Transaction", iterations: 3 },
    };
    setNodes((current) => [...current, { ...defaults[type], id, x: 60, y: newY }]);
    setSelectedNodeId(id);
  };

  const deleteNode = (id: string) => {
    if (nodes.length <= 1) return;
    setNodes((current) => current.filter((node) => node.id !== id));
    if (selectedNodeId === id) setSelectedNodeId(nodes[0].id);
  };

  const updateNodeProperty = (key: keyof FlowNode, value: FlowNode[keyof FlowNode]) => {
    setNodes((current) => current.map((node) => node.id === selectedNodeId ? { ...node, [key]: value } : node));
  };

  const generateLocustCode = (): string => {
    let tasksCode = "";
    nodes.forEach((node) => {
      if (node.type === "http") {
        const method = (node.method || "GET").toLowerCase();
        tasksCode += method === "post" && node.payload
          ? `        # ${node.title}\n        self.client.${method}("${node.path || "/"}", json=${node.payload}, name="${node.title}")\n`
          : `        # ${node.title}\n        self.client.${method}("${node.path || "/"}", name="${node.title}")\n`;
      } else if (node.type === "think_time") {
        tasksCode += `        # Think time: ${node.delaySeconds || 1}s\n        import time; time.sleep(${node.delaySeconds || 1})\n`;
      }
    });
    return `"""
Generated by Loom Visual Flow Designer
Target Host: ${targetHost || "http://localhost:8080"}
"""

from locust import HttpUser, task, between

class VisualFlowUser(HttpUser):
    wait_time = between(1.0, 2.5)

    @task
    def execute_flow_scenario(self):
${tasksCode || '        self.client.get("/", name="Homepage")\n'}
`;
  };

  const generateK6Code = (): string => {
    let stepsCode = "";
    nodes.forEach((node) => {
      if (node.type === "http") {
        const method = (node.method || "GET").toLowerCase();
        stepsCode += method === "post"
          ? `  // ${node.title}\n  let res = http.post(target + '${node.path || "/"}', '${node.payload || "{}"}', { headers: { 'Content-Type': 'application/json' } });\n  check(res, { '${node.title} 200': (r) => r.status === 200 });\n`
          : `  // ${node.title}\n  let res = http.get(target + '${node.path || "/"}');\n  check(res, { '${node.title} 200': (r) => r.status === 200 });\n`;
      } else if (node.type === "think_time") {
        stepsCode += `  sleep(${node.delaySeconds || 1});\n`;
      }
    });
    return `// Generated by Loom Visual Flow Designer
import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
    { duration: '10s', target: 20 },
    { duration: '30s', target: 20 },
    { duration: '5s', target: 0 },
  ],
};

const target = __ENV.TARGET_HOST || '${targetHost || "http://localhost:8080"}';

export default function () {
${stepsCode}
}
`;
  };

  const activeGeneratedScript = previewLanguage === "locust" ? generateLocustCode() : generateK6Code();
  const copyScript = async () => {
    await navigator.clipboard.writeText(activeGeneratedScript);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  return (
    <main className="loom-flow-builder" aria-label="Visual flow builder">
      <aside className="loom-node-palette" aria-label="Add scenario nodes">
        <p className="loom-overline">Add scenario nodes</p>
        {(Object.keys(nodeDetails) as Array<Exclude<FlowNode["type"], "start">>).map((type) => {
          const detail = nodeDetails[type];
          const Icon = detail.icon;
          return (
            <button key={type} type="button" className="loom-node-palette__button" onClick={() => addNode(type)}>
              <span className="loom-node-palette__icon"><Icon aria-hidden="true" /></span>
              <span><strong>{detail.label}</strong><small>{detail.detail}</small></span>
            </button>
          );
        })}
        <div className="loom-node-palette__hint">
          <Sparkles aria-hidden="true" />
          <strong>Interactive graph</strong>
          <span>Nodes execute sequentially to simulate a user workflow under load.</span>
        </div>
      </aside>

      <section className="loom-canvas" aria-label="Scenario canvas">
        <div className="loom-canvas__flow">
          {nodes.map((node, index) => (
            <div className="loom-canvas__step" key={node.id}>
              <div className="loom-canvas__node-row">
                <button
                  type="button"
                  className={`loom-node ${selectedNodeId === node.id ? "loom-node--selected" : ""}`}
                  onClick={() => setSelectedNodeId(node.id)}
                  aria-pressed={selectedNodeId === node.id}
                >
                  <span className="loom-node__title">
                    {node.type === "start" && <span className="loom-node__start-dot" aria-hidden="true" />}
                    {node.type === "http" && <span className="loom-node__method">{node.method || "GET"}</span>}
                    {node.type === "think_time" && <Clock aria-hidden="true" />}
                    {node.type === "assertion" && <CheckCircle aria-hidden="true" />}
                    {node.type === "loop" && <Repeat aria-hidden="true" />}
                    <strong>{node.title}</strong>
                  </span>
                  <span className="loom-node__detail">
                    {node.type === "http" && (node.path || "/")}
                    {node.type === "think_time" && `Wait ${node.delaySeconds || 1}s delay`}
                    {node.type === "assertion" && `Status == ${node.expectedStatus || 200}, <${node.maxLatencyMs || 500}ms`}
                    {node.type === "loop" && `Repeat ${node.iterations || 3} times`}
                    {node.type === "start" && "Concurrent load profile generator"}
                  </span>
                </button>
                {node.type !== "start" && (
                  <button type="button" className="loom-icon-button loom-node__delete" onClick={() => deleteNode(node.id)} aria-label={`Delete ${node.title}`}>
                    <Trash2 aria-hidden="true" />
                  </button>
                )}
              </div>
              {index < nodes.length - 1 && <span className="loom-canvas__connector" aria-hidden="true" />}
            </div>
          ))}
        </div>
      </section>

      <aside className="loom-flow-inspector" aria-label="Step inspector">
        <header className="loom-flow-inspector__header">
          <span><Layers aria-hidden="true" /> Step inspector</span>
          <LoomButton className="loom-button--compact" onClick={() => onExportToRunner(activeGeneratedScript, previewLanguage)}>
            <Send aria-hidden="true" /> Send to Runner
          </LoomButton>
        </header>
        <section className="loom-flow-inspector__fields">
          <label className="loom-form-field">Step title
            <input value={selectedNode.title} onChange={(event) => updateNodeProperty("title", event.target.value)} />
          </label>
          {selectedNode.type === "http" && <>
            <label className="loom-form-field">Method
              <select value={selectedNode.method || "GET"} onChange={(event) => updateNodeProperty("method", event.target.value as FlowNode["method"])}>
                <option value="GET">GET</option><option value="POST">POST</option><option value="PUT">PUT</option><option value="DELETE">DELETE</option>
              </select>
            </label>
            <label className="loom-form-field">Endpoint path
              <input value={selectedNode.path || "/"} placeholder="/api/v1/..." onChange={(event) => updateNodeProperty("path", event.target.value)} />
            </label>
            {selectedNode.method === "POST" && <label className="loom-form-field">JSON payload
              <textarea rows={3} value={selectedNode.payload || "{}"} onChange={(event) => updateNodeProperty("payload", event.target.value)} />
            </label>}
          </>}
          {selectedNode.type === "think_time" && <label className="loom-form-field">Delay duration (seconds)
            <input type="number" min="0.1" step="0.5" value={selectedNode.delaySeconds || 1} onChange={(event) => updateNodeProperty("delaySeconds", Number(event.target.value) || 1)} />
          </label>}
          {selectedNode.type === "assertion" && <div className="loom-form-field-row">
            <label className="loom-form-field">Status code
              <input type="number" value={selectedNode.expectedStatus || 200} onChange={(event) => updateNodeProperty("expectedStatus", Number(event.target.value) || 200)} />
            </label>
            <label className="loom-form-field">Max latency (ms)
              <input type="number" value={selectedNode.maxLatencyMs || 500} onChange={(event) => updateNodeProperty("maxLatencyMs", Number(event.target.value) || 500)} />
            </label>
          </div>}
          {selectedNode.type === "loop" && <label className="loom-form-field">Iterations
            <input type="number" min="1" value={selectedNode.iterations || 3} onChange={(event) => updateNodeProperty("iterations", Number(event.target.value) || 1)} />
          </label>}
        </section>
        <section className="loom-code-preview" aria-label="Generated code">
          <header className="loom-code-preview__header">
            <span><FileCode aria-hidden="true" /> Generated code</span>
            <div className="loom-code-preview__controls">
              <button type="button" className={previewLanguage === "locust" ? "is-active" : ""} onClick={() => setPreviewLanguage("locust")}>Python (Locust)</button>
              <button type="button" className={previewLanguage === "k6" ? "is-active" : ""} onClick={() => setPreviewLanguage("k6")}>JS (k6)</button>
              <button type="button" className="loom-code-preview__copy" onClick={copyScript} aria-label="Copy generated code">
                {copiedScript ? <Check aria-hidden="true" /> : <Copy aria-hidden="true" />} {copiedScript ? "Copied" : "Copy"}
              </button>
            </div>
          </header>
          <pre>{activeGeneratedScript}</pre>
        </section>
      </aside>
    </main>
  );
};
