# Generated by Loom Visual Flow Designer
# Target Host: http://localhost:8080

import json
import time
from locust import HttpUser, task, between

class VisualFlowUser(HttpUser):
    wait_time = between(1.0, 2.5)

    @task
    def execute_flow_scenario(self):
        last_response = None
        # Homepage Browse
        last_response = self.client.get("/", name="Homepage Browse")
        # Think time: 2s
        time.sleep(2)
        # User Login Action
        last_response = self.client.post("/api/v1/auth/login", json=json.loads("{\"username\": \"test_user\", \"password\": \"secure_password\"}"), name="User Login Action")
        if last_response is None:
            raise AssertionError("Verify 200 OK & Latency < 400ms: no preceding HTTP response")
        if last_response.status_code != 200:
            raise AssertionError("Verify 200 OK & Latency < 400ms: expected 200, got " + str(last_response.status_code))
        if last_response.elapsed.total_seconds() * 1000 > 400:
            raise AssertionError("Verify 200 OK & Latency < 400ms: response exceeded 400ms")

